### PR TITLE
Add a compile_error that says cargo-lipo only works on macOS.

### PR DESCRIPTION
**Pull request by isislovecruft**
This implements the suggestion in https://github.com/TimNN/cargo-lipo/issues/10

### CODE REVIEW

**Comment by isislovecruft** [comment]
Oh I guess this will break CI, I'll add a `#[cfg(not(test))]` in there.

**Comment by TimNN** [comment]
Thanks for your PR!

I would prefer to just print a big warning if we are not on macOS when `cargo-lipo` is run. Also, I have personally never needed to set `DEVELOPER_DIR`, is this a recent requirement? Is that always required?

**Comment by isislovecruft** [comment]
> Also, I have personally never needed to set DEVELOPER_DIR, is this a recent requirement? Is that always required?

Not entirely sure.. you may have permanently done the equivalent in the past by doing `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`? Or it might only be that this is required for linking against the correct libraries later, if using the compiled universal library in an Xcode Swift project? It definitely didn't work without it, but this was also on an entirely new Macbook with an entirely new copy of Xcode and new terminal (I'd never used MacOS before), so I'd lean towards believing this was some sort of "do it once when you set up your dev environment and then forget you ever did it" thing. I can take that out if no one else seems to need to do that.

> I would prefer to just print a big warning if we are not on macOS when cargo-lipo is run.

Sure, no problem! I've amended the commit to do that instead.

**Comment by TimNN** [comment]
Thanks!

**Pull request merged**
