### PR TITLE
Update lipo command to accept a package name

### PR DESCRIPTION
**Pull request by fluffyemily**
We have moved our FFI boundary into a subcrate as we only need to build our code as a library for deployment on iOS and Android. However, once that was done we were no longer able to use `cargo lipo` in order to build our universal iOS library. I amended `cargo-lipo` to take an optional `--package` argument in order to specify a package in which to find the library. I thought you might find it useful.

### CODE REVIEW

**Comment by TimNN** [comment]
Hi @fluffyemily, thanks for the PR. First two questions: (1) does `cargo lipo` work if you execute it in the directory of the subcrate? (2) are you using cargo workspaces?

There is a small issue with the PR as is: `cargo lipo` no longer works if it is executed in a subdirectory (e.g. `project/src` instead of `project`). This could probably be fixed by not passing a `manifest-path` to cargo if no package was specified.

**Comment by fluffyemily** [comment]
Hi @TimNN 

I tried executing `cargo lipo` inside the subcrate directory as my first avenue of exploration and I found that resulted in the error: `Failed to verify target directory: No such file or directory (os error 2)`. I therefore started exploring other options (including the package as an arg to lipo). I did consider passing in the target directory location as an arg instead, but figured this would be more useful overall.

I'll take a look at the `project/src` instance - I have to confess I didn't think about that.

**Comment by TimNN** [comment]
@fluffyemily: Alright, I looked into the issue. My preferred solution would be to

1) remove the `--package` flag
2) if available, use the `cargo metadata` command to locate the `target` directory (this is what currently fails)
3) if `cargo metadata` is not available, fall back to the current behavior

Are you interested in implementing that? If not I'll try to get this done by next Monday.

**Comment by fluffyemily** [comment]
I can take a look at this today.  Thanks for your input.

**Comment by fluffyemily** [comment]
BTW, I still think a package arg is a good idea as it enables standard cargo args to be added to `cargo lipo` commands. `--package` and `--all` should be valid options and will produce behaviour that cargo users would be familiar with.

**Comment by TimNN** [comment]
Sure, if it behaves the same way as for normal Cargo I’d be fine with adding a “package” Argument. However IIRC (on mobile right now), the implementation of this PR interpreted the argmuent to “package” more like a “path to the crate root” rather than a “crate name” (which is what cargo does, I assume).

**Comment by fluffyemily** [comment]
Yeah, I'll take a look at that PR. For the actual building of the project it passes the package arg into the cargo build command. The bit that needs working out if the path to the `toml` file that is required as the `manifest-path` in order to make `read-manifest` work for the correct subdir (no package arg for `read-manifest`. I'll make that bit more elegant and resubmit.

**Comment by TimNN** [comment]
Mh, looking some more at the `cargo metadata` output, I think we can get all the info we want directly from there (at least for modern `cargo` versions, I just noticed that `target_directory, at least, is missing from `cargo v1.16`):

* We have the `target_directory`
* We have `packages[?].name` to find the package passed to `--package`
* We have `workspace_members` for `--all` and to check against `packages[?].id`
* We have `packages[?].manifest_path` (although I don't think we need that any longer
* We have `packages[?].targets` (to find the `staticlib`)
* We have `resolve.root`, which contains the id of the "active" crate

**Pull request closed without merging**
