### PR TITLE
Add awareness of the new simulator platform SDK

### LINKED ISSUE #52: Xcode 13 and M1 chips introduce a new SDK for simulation builds
With Xcode 13 on M1 chips, there is a new SDK used for simulator builds on aarch64 (that is, the SDK is different from builds that run on actual hardware).  Rust supports this new SDK with the `-sim` ABI addition to the `aarch64-apple-ios` triple, so builds whose platform contains the word "simulator" (as in "iphonesimulator" as opposed to "iphoneos") need to be done with the `aarch64-apple-ios-sim` target.

Complicating this is the fact that lipo doesn't distinguish these libraries from other aarch64 libraries, so it can't put a _simulator_ SDK library and a _standard_ SDK library in the same archive.  Thus there's no way to build all the architectures into one library.

It's not exactly clear how lipo could handle this outside of the Xcode integration context.  But at least in that context it should be able to choose the right library based on the targets being built.  I'm going to submit a PR to ad this little logic.

### PR DESCRIPTION
**Pull request by brotskydotcom**
This PR fixes #52, which has the details of the problem.  It also updates the README instructions about XCode integration and fixes an old compiler warning.

### CODE REVIEW

**Comment by brotskydotcom** [comment]
Hi @TimNN, I believe this PR is ready for review.  `cargo-lipo` is still incredibly useful and this updates it to work well with Xcode 13 and the new rust-supported iPhone simulator ABI.

**Comment by TimNN** [comment]
Hi @brotskydotcom, thanks for the PR! Just as a heads-up, I probably won't have the time to properly look at the PR until next weekend or the weekend after. Thanks for your patience!

**Comment by adobeDan** [comment]
No worries, @TimNN!  I want to do some more testing on Intel anyway, so I will probably make some changes before you have a chance to review.

**Comment by brotskydotcom** [comment]
Thanks, @TimNN, and no worries!  I'm updating the PR based on x64-based testing so one or two weeks from now is just fine, thanks!

**Comment by TimNN** [comment]
Thank you for your patience! This looks good, with two nits:

1) Can you please add short explanation to the readme why the "delete Rust static libraries" step is necessary? (I assume it's because of the "can't include two arm64 targets in one archive" issue).

2) Can you please run rustfmt? (See also the failed CI checks, which are running now).

Also, I'm picking up your https://github.com/TimNN/cargo-lipo/pull/53/commits/0999f20250bb9ee09175d3a9ce1bd024081c0f2c in a separate PR to fix CI, the `macos` tests seem to need some maintenance.

**Comment by brotskydotcom** [comment]
Hi @TimNN, thanks for the review!  I've pushed a commit to fix both those issues.  By the way, you might be interested:
- your claim that cargo-lipo in its current form shouldn't be needed for iOS integration is quite correct.  The trick of deleting the built library can be used (together with copying the correct pre-built library) to integrate cargo directly with Xcode.  I've provided a pointer in the updated README to a project that shows how to do this.
- I had a real "face palm" moment when I saw your comment about running the rust formatter.  That's actually my default setting for all my projects, but while I was preparing this PR I was also working on iOS support for the rust-system-framework project, and the developers there don't like what the rust formatter does, so I had to turn it off.  Thanks for the reminder to turn it back on!

**Comment by TimNN** [comment]
Thanks! I'll see about releasing a new version later today.

**Pull request merged**
